// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package puma_accel_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 7;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic q;
    logic qe;
  } puma_accel_reg2hw_ctrl_reg_t;

  typedef struct packed {
    logic [7:0] q;
    logic       qe;
  } puma_accel_reg2hw_imem_addr_reg_t;

  typedef struct packed {logic [31:0] q;} puma_accel_reg2hw_imem_data_reg_t;

  typedef struct packed {logic q;} puma_accel_reg2hw_imem_write_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } puma_accel_reg2hw_imem_push_reg_t;

  typedef struct packed {logic [9:0] q;} puma_accel_reg2hw_vreg_sel_reg_t;

  typedef struct packed {logic q;} puma_accel_reg2hw_imem_prog_bank_reg_t;

  typedef struct packed {logic q;} puma_accel_reg2hw_imem_exec_bank_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } puma_accel_reg2hw_imem_push_commit_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } puma_accel_reg2hw_resident_push_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } puma_accel_reg2hw_resident_fifo_push_reg_t;

  typedef struct packed {
    logic [1:0] d;
    logic       de;
  } puma_accel_hw2reg_status_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } puma_accel_hw2reg_vreg_data_reg_t;

  typedef struct packed {
    logic [7:0] d;
    logic       de;
  } puma_accel_hw2reg_pc_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } puma_accel_hw2reg_ir_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } puma_accel_hw2reg_perf_total_cycles_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } puma_accel_hw2reg_perf_instr_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } puma_accel_hw2reg_perf_load_cycles_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } puma_accel_hw2reg_perf_store_cycles_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } puma_accel_hw2reg_perf_wstore_cycles_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } puma_accel_hw2reg_perf_mvm_cycles_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } puma_accel_hw2reg_imem_active_bank_reg_t;

  typedef struct packed {
    logic [1:0] d;
    logic       de;
  } puma_accel_hw2reg_resident_status_reg_t;

  typedef struct packed {
    logic [8:0] d;
    logic       de;
  } puma_accel_hw2reg_resident_fifo_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    puma_accel_reg2hw_ctrl_reg_t ctrl;  // [187:186]
    puma_accel_reg2hw_imem_addr_reg_t imem_addr;  // [185:177]
    puma_accel_reg2hw_imem_data_reg_t imem_data;  // [176:145]
    puma_accel_reg2hw_imem_write_reg_t imem_write;  // [144:144]
    puma_accel_reg2hw_imem_push_reg_t imem_push;  // [143:111]
    puma_accel_reg2hw_vreg_sel_reg_t vreg_sel;  // [110:101]
    puma_accel_reg2hw_imem_prog_bank_reg_t imem_prog_bank;  // [100:100]
    puma_accel_reg2hw_imem_exec_bank_reg_t imem_exec_bank;  // [99:99]
    puma_accel_reg2hw_imem_push_commit_reg_t imem_push_commit;  // [98:66]
    puma_accel_reg2hw_resident_push_reg_t resident_push;  // [65:33]
    puma_accel_reg2hw_resident_fifo_push_reg_t resident_fifo_push;  // [32:0]
  } puma_accel_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    puma_accel_hw2reg_status_reg_t status;  // [274:272]
    puma_accel_hw2reg_vreg_data_reg_t vreg_data;  // [271:255]
    puma_accel_hw2reg_pc_reg_t pc;  // [254:246]
    puma_accel_hw2reg_ir_reg_t ir;  // [245:213]
    puma_accel_hw2reg_perf_total_cycles_reg_t perf_total_cycles;  // [212:180]
    puma_accel_hw2reg_perf_instr_reg_t perf_instr;  // [179:147]
    puma_accel_hw2reg_perf_load_cycles_reg_t perf_load_cycles;  // [146:114]
    puma_accel_hw2reg_perf_store_cycles_reg_t perf_store_cycles;  // [113:81]
    puma_accel_hw2reg_perf_wstore_cycles_reg_t perf_wstore_cycles;  // [80:48]
    puma_accel_hw2reg_perf_mvm_cycles_reg_t perf_mvm_cycles;  // [47:15]
    puma_accel_hw2reg_imem_active_bank_reg_t imem_active_bank;  // [14:13]
    puma_accel_hw2reg_resident_status_reg_t resident_status;  // [12:10]
    puma_accel_hw2reg_resident_fifo_status_reg_t resident_fifo_status;  // [9:0]
  } puma_accel_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PUMA_ACCEL_CTRL_OFFSET = 7'h0;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_STATUS_OFFSET = 7'h4;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IMEM_ADDR_OFFSET = 7'h8;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IMEM_DATA_OFFSET = 7'hc;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IMEM_WRITE_OFFSET = 7'h10;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IMEM_PUSH_OFFSET = 7'h14;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_VREG_SEL_OFFSET = 7'h18;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_VREG_DATA_OFFSET = 7'h1c;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_PC_OFFSET = 7'h20;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IR_OFFSET = 7'h24;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_PERF_TOTAL_CYCLES_OFFSET = 7'h28;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_PERF_INSTR_OFFSET = 7'h2c;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_PERF_LOAD_CYCLES_OFFSET = 7'h30;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_PERF_STORE_CYCLES_OFFSET = 7'h34;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_PERF_WSTORE_CYCLES_OFFSET = 7'h38;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_PERF_MVM_CYCLES_OFFSET = 7'h3c;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IMEM_PROG_BANK_OFFSET = 7'h40;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IMEM_EXEC_BANK_OFFSET = 7'h44;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IMEM_ACTIVE_BANK_OFFSET = 7'h48;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_IMEM_PUSH_COMMIT_OFFSET = 7'h4c;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_RESIDENT_PUSH_OFFSET = 7'h50;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_RESIDENT_STATUS_OFFSET = 7'h54;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_RESIDENT_FIFO_PUSH_OFFSET = 7'h58;
  parameter logic [BlockAw-1:0] PUMA_ACCEL_RESIDENT_FIFO_STATUS_OFFSET = 7'h5c;

  // Register index
  typedef enum int {
    PUMA_ACCEL_CTRL,
    PUMA_ACCEL_STATUS,
    PUMA_ACCEL_IMEM_ADDR,
    PUMA_ACCEL_IMEM_DATA,
    PUMA_ACCEL_IMEM_WRITE,
    PUMA_ACCEL_IMEM_PUSH,
    PUMA_ACCEL_VREG_SEL,
    PUMA_ACCEL_VREG_DATA,
    PUMA_ACCEL_PC,
    PUMA_ACCEL_IR,
    PUMA_ACCEL_PERF_TOTAL_CYCLES,
    PUMA_ACCEL_PERF_INSTR,
    PUMA_ACCEL_PERF_LOAD_CYCLES,
    PUMA_ACCEL_PERF_STORE_CYCLES,
    PUMA_ACCEL_PERF_WSTORE_CYCLES,
    PUMA_ACCEL_PERF_MVM_CYCLES,
    PUMA_ACCEL_IMEM_PROG_BANK,
    PUMA_ACCEL_IMEM_EXEC_BANK,
    PUMA_ACCEL_IMEM_ACTIVE_BANK,
    PUMA_ACCEL_IMEM_PUSH_COMMIT,
    PUMA_ACCEL_RESIDENT_PUSH,
    PUMA_ACCEL_RESIDENT_STATUS,
    PUMA_ACCEL_RESIDENT_FIFO_PUSH,
    PUMA_ACCEL_RESIDENT_FIFO_STATUS
  } puma_accel_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PUMA_ACCEL_PERMIT[24] = '{
      4'b0001,  // index[ 0] PUMA_ACCEL_CTRL
      4'b0001,  // index[ 1] PUMA_ACCEL_STATUS
      4'b0001,  // index[ 2] PUMA_ACCEL_IMEM_ADDR
      4'b1111,  // index[ 3] PUMA_ACCEL_IMEM_DATA
      4'b0001,  // index[ 4] PUMA_ACCEL_IMEM_WRITE
      4'b1111,  // index[ 5] PUMA_ACCEL_IMEM_PUSH
      4'b0011,  // index[ 6] PUMA_ACCEL_VREG_SEL
      4'b0011,  // index[ 7] PUMA_ACCEL_VREG_DATA
      4'b0001,  // index[ 8] PUMA_ACCEL_PC
      4'b1111,  // index[ 9] PUMA_ACCEL_IR
      4'b1111,  // index[10] PUMA_ACCEL_PERF_TOTAL_CYCLES
      4'b1111,  // index[11] PUMA_ACCEL_PERF_INSTR
      4'b1111,  // index[12] PUMA_ACCEL_PERF_LOAD_CYCLES
      4'b1111,  // index[13] PUMA_ACCEL_PERF_STORE_CYCLES
      4'b1111,  // index[14] PUMA_ACCEL_PERF_WSTORE_CYCLES
      4'b1111,  // index[15] PUMA_ACCEL_PERF_MVM_CYCLES
      4'b0001,  // index[16] PUMA_ACCEL_IMEM_PROG_BANK
      4'b0001,  // index[17] PUMA_ACCEL_IMEM_EXEC_BANK
      4'b0001,  // index[18] PUMA_ACCEL_IMEM_ACTIVE_BANK
      4'b1111,  // index[19] PUMA_ACCEL_IMEM_PUSH_COMMIT
      4'b1111,  // index[20] PUMA_ACCEL_RESIDENT_PUSH
      4'b0001,  // index[21] PUMA_ACCEL_RESIDENT_STATUS
      4'b1111,  // index[22] PUMA_ACCEL_RESIDENT_FIFO_PUSH
      4'b0011  // index[23] PUMA_ACCEL_RESIDENT_FIFO_STATUS
  };

endpackage
