// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module puma_accel_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 7
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output puma_accel_reg_pkg::puma_accel_reg2hw_t reg2hw,  // Write
    input puma_accel_reg_pkg::puma_accel_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import puma_accel_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic               reg_we;
  logic               reg_re;
  logic [BlockAw-1:0] reg_addr;
  logic [     DW-1:0] reg_wdata;
  logic [    DBW-1:0] reg_be;
  logic [     DW-1:0] reg_rdata;
  logic               reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_qs;
  logic ctrl_wd;
  logic ctrl_we;
  logic [1:0] status_qs;
  logic [7:0] imem_addr_qs;
  logic [7:0] imem_addr_wd;
  logic imem_addr_we;
  logic [31:0] imem_data_qs;
  logic [31:0] imem_data_wd;
  logic imem_data_we;
  logic imem_write_qs;
  logic imem_write_wd;
  logic imem_write_we;
  logic [31:0] imem_push_qs;
  logic [31:0] imem_push_wd;
  logic imem_push_we;
  logic [9:0] vreg_sel_qs;
  logic [9:0] vreg_sel_wd;
  logic vreg_sel_we;
  logic [15:0] vreg_data_qs;
  logic [7:0] pc_qs;
  logic [31:0] ir_qs;
  logic [31:0] perf_total_cycles_qs;
  logic [31:0] perf_instr_qs;
  logic [31:0] perf_load_cycles_qs;
  logic [31:0] perf_store_cycles_qs;
  logic [31:0] perf_wstore_cycles_qs;
  logic [31:0] perf_mvm_cycles_qs;
  logic imem_prog_bank_qs;
  logic imem_prog_bank_wd;
  logic imem_prog_bank_we;
  logic imem_exec_bank_qs;
  logic imem_exec_bank_wd;
  logic imem_exec_bank_we;
  logic imem_active_bank_qs;
  logic [31:0] imem_push_commit_qs;
  logic [31:0] imem_push_commit_wd;
  logic imem_push_commit_we;
  logic [31:0] resident_push_qs;
  logic [31:0] resident_push_wd;
  logic resident_push_we;
  logic [1:0] resident_status_qs;
  logic [31:0] resident_fifo_push_qs;
  logic [31:0] resident_fifo_push_wd;
  logic resident_fifo_push_we;
  logic [8:0] resident_fifo_status_qs;

  // Register instances
  // R[ctrl]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_ctrl (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ctrl_we),
      .wd(ctrl_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(reg2hw.ctrl.qe),
      .q (reg2hw.ctrl.q),

      // to register interface (read)
      .qs(ctrl_qs)
  );


  // R[status]: V(False)

  prim_subreg #(
      .DW      (2),
      .SWACCESS("RO"),
      .RESVAL  (2'h0)
  ) u_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.status.de),
      .d (hw2reg.status.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(status_qs)
  );


  // R[imem_addr]: V(False)

  prim_subreg #(
      .DW      (8),
      .SWACCESS("RW"),
      .RESVAL  (8'h0)
  ) u_imem_addr (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(imem_addr_we),
      .wd(imem_addr_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(reg2hw.imem_addr.qe),
      .q (reg2hw.imem_addr.q),

      // to register interface (read)
      .qs(imem_addr_qs)
  );


  // R[imem_data]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_imem_data (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(imem_data_we),
      .wd(imem_data_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.imem_data.q),

      // to register interface (read)
      .qs(imem_data_qs)
  );


  // R[imem_write]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_imem_write (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(imem_write_we),
      .wd(imem_write_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.imem_write.q),

      // to register interface (read)
      .qs(imem_write_qs)
  );


  // R[imem_push]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_imem_push (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(imem_push_we),
      .wd(imem_push_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(reg2hw.imem_push.qe),
      .q (reg2hw.imem_push.q),

      // to register interface (read)
      .qs(imem_push_qs)
  );


  // R[vreg_sel]: V(False)

  prim_subreg #(
      .DW      (10),
      .SWACCESS("RW"),
      .RESVAL  (10'h0)
  ) u_vreg_sel (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(vreg_sel_we),
      .wd(vreg_sel_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.vreg_sel.q),

      // to register interface (read)
      .qs(vreg_sel_qs)
  );


  // R[vreg_data]: V(False)

  prim_subreg #(
      .DW      (16),
      .SWACCESS("RO"),
      .RESVAL  (16'h0)
  ) u_vreg_data (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.vreg_data.de),
      .d (hw2reg.vreg_data.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(vreg_data_qs)
  );


  // R[pc]: V(False)

  prim_subreg #(
      .DW      (8),
      .SWACCESS("RO"),
      .RESVAL  (8'h0)
  ) u_pc (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.pc.de),
      .d (hw2reg.pc.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(pc_qs)
  );


  // R[ir]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_ir (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.ir.de),
      .d (hw2reg.ir.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(ir_qs)
  );


  // R[perf_total_cycles]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_perf_total_cycles (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.perf_total_cycles.de),
      .d (hw2reg.perf_total_cycles.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(perf_total_cycles_qs)
  );


  // R[perf_instr]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_perf_instr (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.perf_instr.de),
      .d (hw2reg.perf_instr.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(perf_instr_qs)
  );


  // R[perf_load_cycles]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_perf_load_cycles (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.perf_load_cycles.de),
      .d (hw2reg.perf_load_cycles.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(perf_load_cycles_qs)
  );


  // R[perf_store_cycles]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_perf_store_cycles (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.perf_store_cycles.de),
      .d (hw2reg.perf_store_cycles.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(perf_store_cycles_qs)
  );


  // R[perf_wstore_cycles]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_perf_wstore_cycles (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.perf_wstore_cycles.de),
      .d (hw2reg.perf_wstore_cycles.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(perf_wstore_cycles_qs)
  );


  // R[perf_mvm_cycles]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_perf_mvm_cycles (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.perf_mvm_cycles.de),
      .d (hw2reg.perf_mvm_cycles.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(perf_mvm_cycles_qs)
  );


  // R[imem_prog_bank]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_imem_prog_bank (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(imem_prog_bank_we),
      .wd(imem_prog_bank_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.imem_prog_bank.q),

      // to register interface (read)
      .qs(imem_prog_bank_qs)
  );


  // R[imem_exec_bank]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_imem_exec_bank (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(imem_exec_bank_we),
      .wd(imem_exec_bank_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.imem_exec_bank.q),

      // to register interface (read)
      .qs(imem_exec_bank_qs)
  );


  // R[imem_active_bank]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_imem_active_bank (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.imem_active_bank.de),
      .d (hw2reg.imem_active_bank.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(imem_active_bank_qs)
  );


  // R[imem_push_commit]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_imem_push_commit (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(imem_push_commit_we),
      .wd(imem_push_commit_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(reg2hw.imem_push_commit.qe),
      .q (reg2hw.imem_push_commit.q),

      // to register interface (read)
      .qs(imem_push_commit_qs)
  );


  // R[resident_push]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_resident_push (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(resident_push_we),
      .wd(resident_push_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(reg2hw.resident_push.qe),
      .q (reg2hw.resident_push.q),

      // to register interface (read)
      .qs(resident_push_qs)
  );


  // R[resident_status]: V(False)

  prim_subreg #(
      .DW      (2),
      .SWACCESS("RO"),
      .RESVAL  (2'h0)
  ) u_resident_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.resident_status.de),
      .d (hw2reg.resident_status.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(resident_status_qs)
  );


  // R[resident_fifo_push]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_resident_fifo_push (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(resident_fifo_push_we),
      .wd(resident_fifo_push_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(reg2hw.resident_fifo_push.qe),
      .q (reg2hw.resident_fifo_push.q),

      // to register interface (read)
      .qs(resident_fifo_push_qs)
  );


  // R[resident_fifo_status]: V(False)

  prim_subreg #(
      .DW      (9),
      .SWACCESS("RO"),
      .RESVAL  (9'h0)
  ) u_resident_fifo_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.resident_fifo_status.de),
      .d (hw2reg.resident_fifo_status.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(resident_fifo_status_qs)
  );




  logic [23:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == PUMA_ACCEL_CTRL_OFFSET);
    addr_hit[1] = (reg_addr == PUMA_ACCEL_STATUS_OFFSET);
    addr_hit[2] = (reg_addr == PUMA_ACCEL_IMEM_ADDR_OFFSET);
    addr_hit[3] = (reg_addr == PUMA_ACCEL_IMEM_DATA_OFFSET);
    addr_hit[4] = (reg_addr == PUMA_ACCEL_IMEM_WRITE_OFFSET);
    addr_hit[5] = (reg_addr == PUMA_ACCEL_IMEM_PUSH_OFFSET);
    addr_hit[6] = (reg_addr == PUMA_ACCEL_VREG_SEL_OFFSET);
    addr_hit[7] = (reg_addr == PUMA_ACCEL_VREG_DATA_OFFSET);
    addr_hit[8] = (reg_addr == PUMA_ACCEL_PC_OFFSET);
    addr_hit[9] = (reg_addr == PUMA_ACCEL_IR_OFFSET);
    addr_hit[10] = (reg_addr == PUMA_ACCEL_PERF_TOTAL_CYCLES_OFFSET);
    addr_hit[11] = (reg_addr == PUMA_ACCEL_PERF_INSTR_OFFSET);
    addr_hit[12] = (reg_addr == PUMA_ACCEL_PERF_LOAD_CYCLES_OFFSET);
    addr_hit[13] = (reg_addr == PUMA_ACCEL_PERF_STORE_CYCLES_OFFSET);
    addr_hit[14] = (reg_addr == PUMA_ACCEL_PERF_WSTORE_CYCLES_OFFSET);
    addr_hit[15] = (reg_addr == PUMA_ACCEL_PERF_MVM_CYCLES_OFFSET);
    addr_hit[16] = (reg_addr == PUMA_ACCEL_IMEM_PROG_BANK_OFFSET);
    addr_hit[17] = (reg_addr == PUMA_ACCEL_IMEM_EXEC_BANK_OFFSET);
    addr_hit[18] = (reg_addr == PUMA_ACCEL_IMEM_ACTIVE_BANK_OFFSET);
    addr_hit[19] = (reg_addr == PUMA_ACCEL_IMEM_PUSH_COMMIT_OFFSET);
    addr_hit[20] = (reg_addr == PUMA_ACCEL_RESIDENT_PUSH_OFFSET);
    addr_hit[21] = (reg_addr == PUMA_ACCEL_RESIDENT_STATUS_OFFSET);
    addr_hit[22] = (reg_addr == PUMA_ACCEL_RESIDENT_FIFO_PUSH_OFFSET);
    addr_hit[23] = (reg_addr == PUMA_ACCEL_RESIDENT_FIFO_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(PUMA_ACCEL_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(PUMA_ACCEL_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(PUMA_ACCEL_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(PUMA_ACCEL_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(PUMA_ACCEL_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(PUMA_ACCEL_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(PUMA_ACCEL_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(PUMA_ACCEL_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(PUMA_ACCEL_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(PUMA_ACCEL_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(PUMA_ACCEL_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(PUMA_ACCEL_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(PUMA_ACCEL_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(PUMA_ACCEL_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(PUMA_ACCEL_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(PUMA_ACCEL_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(PUMA_ACCEL_PERMIT[16] & ~reg_be))) |
               (addr_hit[17] & (|(PUMA_ACCEL_PERMIT[17] & ~reg_be))) |
               (addr_hit[18] & (|(PUMA_ACCEL_PERMIT[18] & ~reg_be))) |
               (addr_hit[19] & (|(PUMA_ACCEL_PERMIT[19] & ~reg_be))) |
               (addr_hit[20] & (|(PUMA_ACCEL_PERMIT[20] & ~reg_be))) |
               (addr_hit[21] & (|(PUMA_ACCEL_PERMIT[21] & ~reg_be))) |
               (addr_hit[22] & (|(PUMA_ACCEL_PERMIT[22] & ~reg_be))) |
               (addr_hit[23] & (|(PUMA_ACCEL_PERMIT[23] & ~reg_be)))));
  end

  assign ctrl_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_wd = reg_wdata[0];

  assign imem_addr_we = addr_hit[2] & reg_we & !reg_error;
  assign imem_addr_wd = reg_wdata[7:0];

  assign imem_data_we = addr_hit[3] & reg_we & !reg_error;
  assign imem_data_wd = reg_wdata[31:0];

  assign imem_write_we = addr_hit[4] & reg_we & !reg_error;
  assign imem_write_wd = reg_wdata[0];

  assign imem_push_we = addr_hit[5] & reg_we & !reg_error;
  assign imem_push_wd = reg_wdata[31:0];

  assign vreg_sel_we = addr_hit[6] & reg_we & !reg_error;
  assign vreg_sel_wd = reg_wdata[9:0];

  assign imem_prog_bank_we = addr_hit[16] & reg_we & !reg_error;
  assign imem_prog_bank_wd = reg_wdata[0];

  assign imem_exec_bank_we = addr_hit[17] & reg_we & !reg_error;
  assign imem_exec_bank_wd = reg_wdata[0];

  assign imem_push_commit_we = addr_hit[19] & reg_we & !reg_error;
  assign imem_push_commit_wd = reg_wdata[31:0];

  assign resident_push_we = addr_hit[20] & reg_we & !reg_error;
  assign resident_push_wd = reg_wdata[31:0];

  assign resident_fifo_push_we = addr_hit[22] & reg_we & !reg_error;
  assign resident_fifo_push_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = ctrl_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[1:0] = status_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[7:0] = imem_addr_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = imem_data_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = imem_write_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = imem_push_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[9:0] = vreg_sel_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[15:0] = vreg_data_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[7:0] = pc_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[31:0] = ir_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = perf_total_cycles_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = perf_instr_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = perf_load_cycles_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[31:0] = perf_store_cycles_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[31:0] = perf_wstore_cycles_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[31:0] = perf_mvm_cycles_qs;
      end

      addr_hit[16]: begin
        reg_rdata_next[0] = imem_prog_bank_qs;
      end

      addr_hit[17]: begin
        reg_rdata_next[0] = imem_exec_bank_qs;
      end

      addr_hit[18]: begin
        reg_rdata_next[0] = imem_active_bank_qs;
      end

      addr_hit[19]: begin
        reg_rdata_next[31:0] = imem_push_commit_qs;
      end

      addr_hit[20]: begin
        reg_rdata_next[31:0] = resident_push_qs;
      end

      addr_hit[21]: begin
        reg_rdata_next[1:0] = resident_status_qs;
      end

      addr_hit[22]: begin
        reg_rdata_next[31:0] = resident_fifo_push_qs;
      end

      addr_hit[23]: begin
        reg_rdata_next[8:0] = resident_fifo_status_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

/* verilator lint_off DECLFILENAME */
module puma_accel_reg_top_intf #(
    parameter  int AW = 7,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output puma_accel_reg_pkg::puma_accel_reg2hw_t reg2hw,  // Write
    input puma_accel_reg_pkg::puma_accel_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  puma_accel_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule
